/* 64K-aligned no-op libsystemd.so.0 stub: real lib is 4K-aligned, unloadable on the 64K-page kernel. sysvinit needs no real systemd. */
long sd_booted(){return 0;}
long sd_bus_add_fallback(){return 0;}
long sd_bus_add_fallback_vtable(){return 0;}
long sd_bus_add_filter(){return 0;}
long sd_bus_add_match(){return 0;}
long sd_bus_add_node_enumerator(){return 0;}
long sd_bus_add_object(){return 0;}
long sd_bus_add_object_manager(){return 0;}
long sd_bus_add_object_vtable(){return 0;}
long sd_bus_attach_event(){return 0;}
long sd_bus_call(){return 0;}
long sd_bus_call_async(){return 0;}
long sd_bus_call_method(){return 0;}
long sd_bus_call_method_async(){return 0;}
long sd_bus_can_send(){return 0;}
long sd_bus_close(){return 0;}
long sd_bus_creds_get_audit_login_uid(){return 0;}
long sd_bus_creds_get_audit_session_id(){return 0;}
long sd_bus_creds_get_augmented_mask(){return 0;}
long sd_bus_creds_get_cgroup(){return 0;}
long sd_bus_creds_get_cmdline(){return 0;}
long sd_bus_creds_get_comm(){return 0;}
long sd_bus_creds_get_description(){return 0;}
long sd_bus_creds_get_egid(){return 0;}
long sd_bus_creds_get_euid(){return 0;}
long sd_bus_creds_get_exe(){return 0;}
long sd_bus_creds_get_fsgid(){return 0;}
long sd_bus_creds_get_fsuid(){return 0;}
long sd_bus_creds_get_gid(){return 0;}
long sd_bus_creds_get_mask(){return 0;}
long sd_bus_creds_get_owner_uid(){return 0;}
long sd_bus_creds_get_pid(){return 0;}
long sd_bus_creds_get_ppid(){return 0;}
long sd_bus_creds_get_selinux_context(){return 0;}
long sd_bus_creds_get_session(){return 0;}
long sd_bus_creds_get_sgid(){return 0;}
long sd_bus_creds_get_slice(){return 0;}
long sd_bus_creds_get_suid(){return 0;}
long sd_bus_creds_get_supplementary_gids(){return 0;}
long sd_bus_creds_get_tid(){return 0;}
long sd_bus_creds_get_tid_comm(){return 0;}
long sd_bus_creds_get_tty(){return 0;}
long sd_bus_creds_get_uid(){return 0;}
long sd_bus_creds_get_unique_name(){return 0;}
long sd_bus_creds_get_unit(){return 0;}
long sd_bus_creds_get_user_slice(){return 0;}
long sd_bus_creds_get_user_unit(){return 0;}
long sd_bus_creds_get_well_known_names(){return 0;}
long sd_bus_creds_has_bounding_cap(){return 0;}
long sd_bus_creds_has_effective_cap(){return 0;}
long sd_bus_creds_has_inheritable_cap(){return 0;}
long sd_bus_creds_has_permitted_cap(){return 0;}
long sd_bus_creds_new_from_pid(){return 0;}
long sd_bus_creds_ref(){return 0;}
long sd_bus_creds_unref(){return 0;}
long sd_bus_default(){return 0;}
long sd_bus_default_flush_close(){return 0;}
long sd_bus_default_system(){return 0;}
long sd_bus_default_user(){return 0;}
long sd_bus_detach_event(){return 0;}
long sd_bus_emit_interfaces_added(){return 0;}
long sd_bus_emit_interfaces_added_strv(){return 0;}
long sd_bus_emit_interfaces_removed(){return 0;}
long sd_bus_emit_interfaces_removed_strv(){return 0;}
long sd_bus_emit_object_added(){return 0;}
long sd_bus_emit_object_removed(){return 0;}
long sd_bus_emit_properties_changed(){return 0;}
long sd_bus_emit_properties_changed_strv(){return 0;}
long sd_bus_emit_signal(){return 0;}
long sd_bus_error_add_map(){return 0;}
long sd_bus_error_copy(){return 0;}
long sd_bus_error_free(){return 0;}
long sd_bus_error_get_errno(){return 0;}
long sd_bus_error_has_name(){return 0;}
long sd_bus_error_is_set(){return 0;}
long sd_bus_error_set(){return 0;}
long sd_bus_error_set_const(){return 0;}
long sd_bus_error_set_errno(){return 0;}
long sd_bus_error_set_errnof(){return 0;}
long sd_bus_error_set_errnofv(){return 0;}
long sd_bus_error_setf(){return 0;}
long sd_bus_flush(){return 0;}
long sd_bus_flush_close_unref(){return 0;}
long sd_bus_get_address(){return 0;}
long sd_bus_get_allow_interactive_authorization(){return 0;}
long sd_bus_get_bus_id(){return 0;}
long sd_bus_get_creds_mask(){return 0;}
long sd_bus_get_current_handler(){return 0;}
long sd_bus_get_current_message(){return 0;}
long sd_bus_get_current_slot(){return 0;}
long sd_bus_get_current_userdata(){return 0;}
long sd_bus_get_description(){return 0;}
long sd_bus_get_event(){return 0;}
long sd_bus_get_events(){return 0;}
long sd_bus_get_exit_on_disconnect(){return 0;}
long sd_bus_get_fd(){return 0;}
long sd_bus_get_name_creds(){return 0;}
long sd_bus_get_name_machine_id(){return 0;}
long sd_bus_get_owner_creds(){return 0;}
long sd_bus_get_property(){return 0;}
long sd_bus_get_property_string(){return 0;}
long sd_bus_get_property_strv(){return 0;}
long sd_bus_get_property_trivial(){return 0;}
long sd_bus_get_scope(){return 0;}
long sd_bus_get_tid(){return 0;}
long sd_bus_get_timeout(){return 0;}
long sd_bus_get_unique_name(){return 0;}
long sd_bus_is_anonymous(){return 0;}
long sd_bus_is_bus_client(){return 0;}
long sd_bus_is_monitor(){return 0;}
long sd_bus_is_open(){return 0;}
long sd_bus_is_server(){return 0;}
long sd_bus_is_trusted(){return 0;}
long sd_bus_list_names(){return 0;}
long sd_bus_message_append(){return 0;}
long sd_bus_message_append_array(){return 0;}
long sd_bus_message_append_array_iovec(){return 0;}
long sd_bus_message_append_array_memfd(){return 0;}
long sd_bus_message_append_array_space(){return 0;}
long sd_bus_message_append_basic(){return 0;}
long sd_bus_message_append_string_iovec(){return 0;}
long sd_bus_message_append_string_memfd(){return 0;}
long sd_bus_message_append_string_space(){return 0;}
long sd_bus_message_append_strv(){return 0;}
long sd_bus_message_at_end(){return 0;}
long sd_bus_message_close_container(){return 0;}
long sd_bus_message_copy(){return 0;}
long sd_bus_message_enter_container(){return 0;}
long sd_bus_message_exit_container(){return 0;}
long sd_bus_message_get_allow_interactive_authorization(){return 0;}
long sd_bus_message_get_auto_start(){return 0;}
long sd_bus_message_get_bus(){return 0;}
long sd_bus_message_get_cookie(){return 0;}
long sd_bus_message_get_creds(){return 0;}
long sd_bus_message_get_destination(){return 0;}
long sd_bus_message_get_errno(){return 0;}
long sd_bus_message_get_error(){return 0;}
long sd_bus_message_get_expect_reply(){return 0;}
long sd_bus_message_get_interface(){return 0;}
long sd_bus_message_get_member(){return 0;}
long sd_bus_message_get_monotonic_usec(){return 0;}
long sd_bus_message_get_path(){return 0;}
long sd_bus_message_get_priority(){return 0;}
long sd_bus_message_get_realtime_usec(){return 0;}
long sd_bus_message_get_reply_cookie(){return 0;}
long sd_bus_message_get_sender(){return 0;}
long sd_bus_message_get_seqnum(){return 0;}
long sd_bus_message_get_signature(){return 0;}
long sd_bus_message_get_type(){return 0;}
long sd_bus_message_has_signature(){return 0;}
long sd_bus_message_is_empty(){return 0;}
long sd_bus_message_is_method_call(){return 0;}
long sd_bus_message_is_method_error(){return 0;}
long sd_bus_message_is_signal(){return 0;}
long sd_bus_message_new_method_call(){return 0;}
long sd_bus_message_new_method_errno(){return 0;}
long sd_bus_message_new_method_errnof(){return 0;}
long sd_bus_message_new_method_error(){return 0;}
long sd_bus_message_new_method_errorf(){return 0;}
long sd_bus_message_new_method_return(){return 0;}
long sd_bus_message_new_signal(){return 0;}
long sd_bus_message_open_container(){return 0;}
long sd_bus_message_peek_type(){return 0;}
long sd_bus_message_read(){return 0;}
long sd_bus_message_read_array(){return 0;}
long sd_bus_message_read_basic(){return 0;}
long sd_bus_message_read_strv(){return 0;}
long sd_bus_message_ref(){return 0;}
long sd_bus_message_rewind(){return 0;}
long sd_bus_message_set_allow_interactive_authorization(){return 0;}
long sd_bus_message_set_auto_start(){return 0;}
long sd_bus_message_set_destination(){return 0;}
long sd_bus_message_set_expect_reply(){return 0;}
long sd_bus_message_set_priority(){return 0;}
long sd_bus_message_skip(){return 0;}
long sd_bus_message_unref(){return 0;}
long sd_bus_message_verify_type(){return 0;}
long sd_bus_negotiate_creds(){return 0;}
long sd_bus_negotiate_fds(){return 0;}
long sd_bus_negotiate_timestamp(){return 0;}
long sd_bus_new(){return 0;}
long sd_bus_open(){return 0;}
long sd_bus_open_system(){return 0;}
long sd_bus_open_system_machine(){return 0;}
long sd_bus_open_system_remote(){return 0;}
long sd_bus_open_user(){return 0;}
long sd_bus_path_decode(){return 0;}
long sd_bus_path_decode_many(){return 0;}
long sd_bus_path_encode(){return 0;}
long sd_bus_path_encode_many(){return 0;}
long sd_bus_process(){return 0;}
long sd_bus_process_priority(){return 0;}
long sd_bus_query_sender_creds(){return 0;}
long sd_bus_query_sender_privilege(){return 0;}
long sd_bus_ref(){return 0;}
long sd_bus_release_name(){return 0;}
long sd_bus_reply_method_errno(){return 0;}
long sd_bus_reply_method_errnof(){return 0;}
long sd_bus_reply_method_error(){return 0;}
long sd_bus_reply_method_errorf(){return 0;}
long sd_bus_reply_method_return(){return 0;}
long sd_bus_request_name(){return 0;}
long sd_bus_send(){return 0;}
long sd_bus_send_to(){return 0;}
long sd_bus_set_address(){return 0;}
long sd_bus_set_allow_interactive_authorization(){return 0;}
long sd_bus_set_anonymous(){return 0;}
long sd_bus_set_bus_client(){return 0;}
long sd_bus_set_description(){return 0;}
long sd_bus_set_exec(){return 0;}
long sd_bus_set_exit_on_disconnect(){return 0;}
long sd_bus_set_fd(){return 0;}
long sd_bus_set_monitor(){return 0;}
long sd_bus_set_property(){return 0;}
long sd_bus_set_server(){return 0;}
long sd_bus_set_trusted(){return 0;}
long sd_bus_slot_get_bus(){return 0;}
long sd_bus_slot_get_current_handler(){return 0;}
long sd_bus_slot_get_current_message(){return 0;}
long sd_bus_slot_get_current_userdata(){return 0;}
long sd_bus_slot_get_description(){return 0;}
long sd_bus_slot_get_userdata(){return 0;}
long sd_bus_slot_ref(){return 0;}
long sd_bus_slot_set_description(){return 0;}
long sd_bus_slot_set_userdata(){return 0;}
long sd_bus_slot_unref(){return 0;}
long sd_bus_start(){return 0;}
long sd_bus_track_add_name(){return 0;}
long sd_bus_track_add_sender(){return 0;}
long sd_bus_track_contains(){return 0;}
long sd_bus_track_count(){return 0;}
long sd_bus_track_count_name(){return 0;}
long sd_bus_track_count_sender(){return 0;}
long sd_bus_track_first(){return 0;}
long sd_bus_track_get_bus(){return 0;}
long sd_bus_track_get_recursive(){return 0;}
long sd_bus_track_get_userdata(){return 0;}
long sd_bus_track_new(){return 0;}
long sd_bus_track_next(){return 0;}
long sd_bus_track_ref(){return 0;}
long sd_bus_track_remove_name(){return 0;}
long sd_bus_track_remove_sender(){return 0;}
long sd_bus_track_set_recursive(){return 0;}
long sd_bus_track_set_userdata(){return 0;}
long sd_bus_track_unref(){return 0;}
long sd_bus_try_close(){return 0;}
long sd_bus_unref(){return 0;}
long sd_bus_wait(){return 0;}
long sd_event_add_child(){return 0;}
long sd_event_add_defer(){return 0;}
long sd_event_add_exit(){return 0;}
long sd_event_add_io(){return 0;}
long sd_event_add_post(){return 0;}
long sd_event_add_signal(){return 0;}
long sd_event_add_time(){return 0;}
long sd_event_default(){return 0;}
long sd_event_dispatch(){return 0;}
long sd_event_exit(){return 0;}
long sd_event_get_exit_code(){return 0;}
long sd_event_get_fd(){return 0;}
long sd_event_get_iteration(){return 0;}
long sd_event_get_state(){return 0;}
long sd_event_get_tid(){return 0;}
long sd_event_get_watchdog(){return 0;}
long sd_event_loop(){return 0;}
long sd_event_new(){return 0;}
long sd_event_now(){return 0;}
long sd_event_prepare(){return 0;}
long sd_event_ref(){return 0;}
long sd_event_run(){return 0;}
long sd_event_set_watchdog(){return 0;}
long sd_event_source_get_child_pid(){return 0;}
long sd_event_source_get_description(){return 0;}
long sd_event_source_get_enabled(){return 0;}
long sd_event_source_get_event(){return 0;}
long sd_event_source_get_io_events(){return 0;}
long sd_event_source_get_io_fd(){return 0;}
long sd_event_source_get_io_revents(){return 0;}
long sd_event_source_get_pending(){return 0;}
long sd_event_source_get_priority(){return 0;}
long sd_event_source_get_signal(){return 0;}
long sd_event_source_get_time(){return 0;}
long sd_event_source_get_time_accuracy(){return 0;}
long sd_event_source_get_time_clock(){return 0;}
long sd_event_source_get_userdata(){return 0;}
long sd_event_source_ref(){return 0;}
long sd_event_source_set_description(){return 0;}
long sd_event_source_set_enabled(){return 0;}
long sd_event_source_set_io_events(){return 0;}
long sd_event_source_set_io_fd(){return 0;}
long sd_event_source_set_prepare(){return 0;}
long sd_event_source_set_priority(){return 0;}
long sd_event_source_set_time(){return 0;}
long sd_event_source_set_time_accuracy(){return 0;}
long sd_event_source_set_userdata(){return 0;}
long sd_event_source_unref(){return 0;}
long sd_event_unref(){return 0;}
long sd_event_wait(){return 0;}
long sd_get_machine_names(){return 0;}
long sd_get_seats(){return 0;}
long sd_get_sessions(){return 0;}
long sd_get_uids(){return 0;}
long sd_id128_from_string(){return 0;}
long sd_id128_get_boot(){return 0;}
long sd_id128_get_invocation(){return 0;}
long sd_id128_get_machine(){return 0;}
long sd_id128_randomize(){return 0;}
long sd_id128_to_string(){return 0;}
long sd_is_fifo(){return 0;}
long sd_is_mq(){return 0;}
long sd_is_socket(){return 0;}
long sd_is_socket_inet(){return 0;}
long sd_is_socket_unix(){return 0;}
long sd_is_special(){return 0;}
long sd_journal_add_conjunction(){return 0;}
long sd_journal_add_disjunction(){return 0;}
long sd_journal_add_match(){return 0;}
long sd_journal_close(){return 0;}
long sd_journal_enumerate_data(){return 0;}
long sd_journal_enumerate_fields(){return 0;}
long sd_journal_enumerate_unique(){return 0;}
long sd_journal_flush_matches(){return 0;}
long sd_journal_get_catalog(){return 0;}
long sd_journal_get_catalog_for_message_id(){return 0;}
long sd_journal_get_cursor(){return 0;}
long sd_journal_get_cutoff_monotonic_usec(){return 0;}
long sd_journal_get_cutoff_realtime_usec(){return 0;}
long sd_journal_get_data(){return 0;}
long sd_journal_get_data_threshold(){return 0;}
long sd_journal_get_events(){return 0;}
long sd_journal_get_fd(){return 0;}
long sd_journal_get_monotonic_usec(){return 0;}
long sd_journal_get_realtime_usec(){return 0;}
long sd_journal_get_timeout(){return 0;}
long sd_journal_get_usage(){return 0;}
long sd_journal_has_persistent_files(){return 0;}
long sd_journal_has_runtime_files(){return 0;}
long sd_journal_next(){return 0;}
long sd_journal_next_skip(){return 0;}
long sd_journal_open(){return 0;}
long sd_journal_open_container(){return 0;}
long sd_journal_open_directory(){return 0;}
long sd_journal_open_directory_fd(){return 0;}
long sd_journal_open_files(){return 0;}
long sd_journal_open_files_fd(){return 0;}
long sd_journal_perror(){return 0;}
long sd_journal_perror_with_location(){return 0;}
long sd_journal_previous(){return 0;}
long sd_journal_previous_skip(){return 0;}
long sd_journal_print(){return 0;}
long sd_journal_print_with_location(){return 0;}
long sd_journal_printv(){return 0;}
long sd_journal_printv_with_location(){return 0;}
long sd_journal_process(){return 0;}
long sd_journal_query_unique(){return 0;}
long sd_journal_reliable_fd(){return 0;}
long sd_journal_restart_data(){return 0;}
long sd_journal_restart_fields(){return 0;}
long sd_journal_restart_unique(){return 0;}
long sd_journal_seek_cursor(){return 0;}
long sd_journal_seek_head(){return 0;}
long sd_journal_seek_monotonic_usec(){return 0;}
long sd_journal_seek_realtime_usec(){return 0;}
long sd_journal_seek_tail(){return 0;}
long sd_journal_send(){return 0;}
long sd_journal_send_with_location(){return 0;}
long sd_journal_sendv(){return 0;}
long sd_journal_sendv_with_location(){return 0;}
long sd_journal_set_data_threshold(){return 0;}
long sd_journal_stream_fd(){return 0;}
long sd_journal_test_cursor(){return 0;}
long sd_journal_wait(){return 0;}
long sd_listen_fds(){return 0;}
long sd_listen_fds_with_names(){return 0;}
long sd_login_monitor_flush(){return 0;}
long sd_login_monitor_get_events(){return 0;}
long sd_login_monitor_get_fd(){return 0;}
long sd_login_monitor_get_timeout(){return 0;}
long sd_login_monitor_new(){return 0;}
long sd_login_monitor_unref(){return 0;}
long sd_machine_get_class(){return 0;}
long sd_machine_get_ifindices(){return 0;}
long sd_notify(){return 0;}
long sd_notifyf(){return 0;}
long sd_peer_get_cgroup(){return 0;}
long sd_peer_get_machine_name(){return 0;}
long sd_peer_get_owner_uid(){return 0;}
long sd_peer_get_session(){return 0;}
long sd_peer_get_slice(){return 0;}
long sd_peer_get_unit(){return 0;}
long sd_peer_get_user_slice(){return 0;}
long sd_peer_get_user_unit(){return 0;}
long sd_pid_get_cgroup(){return 0;}
long sd_pid_get_machine_name(){return 0;}
long sd_pid_get_owner_uid(){return 0;}
long sd_pid_get_session(){return 0;}
long sd_pid_get_slice(){return 0;}
long sd_pid_get_unit(){return 0;}
long sd_pid_get_user_slice(){return 0;}
long sd_pid_get_user_unit(){return 0;}
long sd_pid_notify(){return 0;}
long sd_pid_notify_with_fds(){return 0;}
long sd_pid_notifyf(){return 0;}
long sd_seat_can_graphical(){return 0;}
long sd_seat_can_multi_session(){return 0;}
long sd_seat_can_tty(){return 0;}
long sd_seat_get_active(){return 0;}
long sd_seat_get_sessions(){return 0;}
long sd_session_get_class(){return 0;}
long sd_session_get_desktop(){return 0;}
long sd_session_get_display(){return 0;}
long sd_session_get_remote_host(){return 0;}
long sd_session_get_remote_user(){return 0;}
long sd_session_get_seat(){return 0;}
long sd_session_get_service(){return 0;}
long sd_session_get_state(){return 0;}
long sd_session_get_tty(){return 0;}
long sd_session_get_type(){return 0;}
long sd_session_get_uid(){return 0;}
long sd_session_get_vt(){return 0;}
long sd_session_is_active(){return 0;}
long sd_session_is_remote(){return 0;}
long sd_uid_get_display(){return 0;}
long sd_uid_get_seats(){return 0;}
long sd_uid_get_sessions(){return 0;}
long sd_uid_get_state(){return 0;}
long sd_uid_is_on_seat(){return 0;}
long sd_watchdog_enabled(){return 0;}
